### ISSUE TITLE
Format of Proposals

### ISSUE THREAD

**Issue by ssakhavi** [hosang/detection-proposals#1]
Hi, 

I have my own proposals and wanted to feed them into the algorithm bu I don't know how to harmonize them so they can be read by your algorithm. 

I have downloaded the precomputed proposals but didn't understand the format in which the proposals are saved. 

Can you please elaborate?

**Comment by hosang** [comment]
I suggest you follow the [benchmark your own method](https://github.com/hosang/detection-proposals#benchmark-your-own-method) section in the readme. By implementing one function (that runs your proposal method) you can generate the data in the right format.

If you really want to know the format of the precomputed proposals, you can read the [documentation that I just added](https://github.com/hosang/detection-proposals#format-of-the-precomputed-proposals) (and the code pointers).

**Comment by ssakhavi** [comment]
Thanks
