### ISSUE TITLE
How to apply this project on KITTI dataset?

### ISSUE THREAD

**Issue by litingfeng** [hosang/detection-proposals#5]
I want to evaluate some detection proposal methods on KITTI dataset. What  should I do? Which files do I  need to change?

**Comment by hosang** [comment]
You have to generate a matfile containing the annotations like the one here `data/pascal_voc07_test_annotations.mat` and then modify the scripts to use the new annotations. Maybe you also have to change the directory structure that the proposals should live in, but that should be all.
