### ISSUE TITLE
How to plot score map & Score-IoU curve?

### ISSUE THREAD

**Issue by litingfeng** [hosang/detection-proposals#6]
In the section 5.1 of the paper, there are score maps and score-IoU plot, but it seems these two are not applied in the project. How to generate them? any code I can reuse ?

**Comment by hosang** [comment]
You can find the plotting code [here](https://github.com/hosang/detection-proposals/blob/master/plot_detector_wiggle_voc07.m) and some more code for generating data [here](https://github.com/hosang/detection-proposals/tree/master/detector_wiggling). 

Hope that helps!
